# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 794b7fde8983c1fd6f73c2d566eb27a4e0e386a6aa4f2cccd2bfde547b49de7783937f9b63dd61d9ca424316d2be03dc4f929e56e29ab8bf14ec7846bf2546e3

test:
  secret_key_base: e251a528319b949a76f26e74ebf4815e5dd1174d7ab1387690ebd5cfa49f6dd29b8431e9d32861510faecb101e7fe914b9d47c1001aa01d2e8c3ee3e09d14aa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 51d40be9223d8a75c7b1ab824830e7bb9663907ff6f2c99133c44fc69a2fa120f55930c00b01cf8b3e0c0e7658476df116de0dcbff3a15eea75f8325180586d1
